### ISSUE TITLE
OC5: internal message blocks the owncloud filesharing app

### ISSUE THREAD

**Issue by merlin2004** [kadukeitor/internal_messages#1]
After the Activation of your app owncloud filesharing not works correctly.

Please check this:

click on a file or folder in owncloud -> share -> share with a public link.
Not happened. I have deactivated your app and all works fine again.
Browser: Firefox on Linux

**Comment by kadukeitor** [comment]
already been solved ... test

**Comment by merlin2004** [comment]
It works now.
Thx
